[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "glib",
  "at-spi2-atk",
  "cups",
  "dbus",
  "expat",
  "libdrm",
  "mesa",
  "libxkbcommon",
  "gtk3",
  "pango",
  "alsa-lib",
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NODE_ENV = "production"
